name: qa_push

on:
  push:
    branches:
      - qa-2024

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: qa-2024
    - name: Send Payload
      run: |
        curl -H "Content-Type: application/json" -X POST -d @$GITHUB_EVENT_PATH ${{ secrets.TEST_WEBHOOK_URL }}
